# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1621, 863)
        self.JarvisUI = QtWidgets.QLabel(Form)
        self.JarvisUI.setGeometry(QtCore.QRect(0, 0, 1591, 851))
        self.JarvisUI.setStyleSheet("C:/Users/lenovo/OneDrive/Desktop/JarvisGui/ironman.gif")
        self.JarvisUI.setText("")
        self.JarvisUI.setPixmap(QtGui.QPixmap("C:/Users/lenovo/OneDrive/Desktop/JarvisGui/ironman.gif"))
        self.JarvisUI.setScaledContents(True)
        self.JarvisUI.setObjectName("JarvisUI")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1160, 720, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(221, 215, 25);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1360, 720, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, -70, 671, 271))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/T8bahf.gif);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/lenovo/OneDrive/Desktop/JarvisGui/initiating.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "RUN"))
        self.pushButton_2.setText(_translate("Form", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
